name: "Provision og deploy til miljø"
on:
  workflow_call:
    inputs:
      environment:
        description: "Environment man vil deploye til"
        required: true
        type: string
env:
  APP_NAME: "orsl-kladdebok"
  WEB_ARTIFACT_NAME: "web-${{ inputs.environment }}"
  APP_SERVICE_PLAN_NAME: "HVI-UTVIKLING-${{ inputs.environment }}-dotnet5-AppServicePlan"
  APP_SERVICE_PLAN_RESOURCE_GROUP_NAME: "HVI-UTVIKLING-${{ inputs.environment }}-FELLES-rg"
jobs:
  deploy:
    name: "Deploy til ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: ${{ inputs.environment }}
    steps:
      - name: Print environment
        run: |
          echo "Deploying to environment: ${{ inputs.environment }}"
          echo "client id: ${{ secrets[format('AZURE_CLIENT_ID_{0}', inputs.environment)] }}"
          echo "tenant id: ${{ secrets[format('AZURE_TENANT_ID_{0}', inputs.environment)] }}"
          echo "subscription id: ${{ secrets[format('AZURE_SUBSCRIPTION_ID_{0}', inputs.environment)] }}"

      - name: Azure Login
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/azure-login@feature/function-as-compaction
        with:
          environment: ${{ inputs.environment }}
          azure-client-id: ${{ secrets[format('AZURE_CLIENT_ID_{0}', inputs.environment)] }}
          azure-tenant-id: ${{ secrets[format('AZURE_TENANT_ID_{0}', inputs.environment)] }}
          azure-subscription-id: ${{ secrets[format('AZURE_SUBSCRIPTION_ID_{0}', inputs.environment)] }}

      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Build angular app
      #   id: build_angular
      #   uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/build/angular-app@feature/function-as-compaction
      #   with:
      #     project-directory: 'web'
      #     artifact-name: "web-${{ inputs.environment }}"

      # - name: Provision angular app service for ${{ inputs.environment }}
      #   id: provision_angular_app_service
      #   uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/provision/app-service@feature/function-as-compaction
      #   with:
      #     environment: ${{ inputs.environment }}
      #     artifact-name: 'web'
      #     app-name: ${{ vars.APP_NAME }}
      #     #set external-access to true if environment is QA or PROD
      #     external-access: ${{ contains(fromJSON('["QA", "PROD"]'), inputs.environment) }}
      #     resource-group: 'HVI-UTV-${{ inputs.environment }}-orsl-kladdebok-rg'
      #     app-service-plan-name: ${{ env.APP_SERVICE_PLAN_NAME }}
      #     app-service-plan-resource-group-name: ${{env.APP_SERVICE_PLAN_RESOURCE_GROUP_NAME}}

      # - name: Provision API app service for ${{ inputs.environment }}
      #   id: provision_api_app_service
      #   uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/provision/app-service@feature/function-as-compaction
      #   with:
      #     environment: ${{ inputs.environment }}
      #     artifact-name: 'api'
      #     app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-api
      #     external-access: false
      #     resource-group: 'HVI-UTV-${{ inputs.environment }}-orsl-kladdebok-rg'    
      #     app-service-plan-name: ${{ env.APP_SERVICE_PLAN_NAME }}
      #     app-service-plan-resource-group-name: ${{env.APP_SERVICE_PLAN_RESOURCE_GROUP_NAME}}

      - name: Provision Function App for ${{ inputs.environment }}
        id: provision_function_app
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/provision/function@feature/function-as-compaction
        with:
          environment: ${{ inputs.environment }}
          function-app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-function
          resource-group: 'HVI-UTV-${{ inputs.environment }}-orsl-kladdebok-rg'
          dotnet-version: 'v9.0'
          storage-account-name: 'orslkladdebok${{ inputs.environment }}sa'

      # - name: Deploy Angular App to ${{ inputs.environment }}
      #   id: deploy_angular
      #   uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/deploy/angular-app@feature/function-as-compaction
      #   with:          
      #     artifact-name: "web-${{ inputs.environment }}"   
      #     app-name: ${{ vars.APP_NAME }}
      #     vars-json: ${{ toJSON(vars) }}


      # - name: "Provision database for ${{ vars.APP_NAME }}-${{ inputs.environment }}-api"
      #   id: provision_api_database
      #   uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/provision/database@feature/function-as-compaction
      #   with:
      #     environment: ${{ inputs.environment }}
      #     database-name: ${{ vars.APP_NAME }}-api-${{ inputs.environment }}-db
      #     sql-server-resource-group: 'HVI-UTVIKLING-${{ inputs.environment }}-FELLES-rg'          
      #     sql-server-name: 'felles-db-server-${{inputs.environment}}-managedid'

      - name: "Provision database for ${{ vars.APP_NAME }}-${{ inputs.environment }}-function"
        id: provision_function_database
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/provision/database@feature/function-as-compaction
        with:
          environment: ${{ inputs.environment }}
          database-name: ${{ vars.APP_NAME }}-function-${{ inputs.environment }}-db
          sql-server-resource-group: 'HVI-UTVIKLING-${{ inputs.environment }}-FELLES-rg'          
          sql-server-name: 'felles-db-server-${{inputs.environment}}-managedid'

      # - name: "Deploy API App to ${{ inputs.environment }}"  
      #   id: deploy_api
      #   uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/deploy/dotnet-app@feature/function-as-compaction
      #   with:
      #     environment: ${{ inputs.environment }}
      #     artifact-name: 'api'
      #     app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-api
      #     connection-string-navn: 'KladdebokDbConnection'
      #     # Using a placeholder for connection string, replace with actual secret or output from DB deployment
      #     connection-string: ${{ steps.provision_api_database.outputs.connection-string }}
      #     cors: 'https://orsl-kladdebok.azurewebsites.net, https://orsl-kladdebok.no'
      #     azure-appsettings: true
      #     vars-json: ${{ toJSON(vars) }}
      #     secrets-json: ${{ toJSON(secrets) }}
      
      - name: "Deploy Function App to ${{ inputs.environment }}"  
        id: deploy_function
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/deploy/dotnet-function-app@feature/function-as-compaction
        with:
          function-app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-function
          environment: ${{ inputs.environment }}
          artifact-name: 'function-app'
          resource-group: 'HVI-UTV-${{ inputs.environment }}-orsl-kladdebok-rg'
          cors: 'https://www.bt.no, https://portal.azure.com, https://nrk.no'
          vars-json: ${{ toJSON(vars) }}
          secrets-json: ${{ toJSON(secrets) }}
          connection-string-navn: 'KladdebokFunctionDbConnection'
          connection-string: ${{ steps.provision_function_database.outputs.connection-string }}

      - name: "Add managed identity to database for ${{ vars.APP_NAME }}-${{ inputs.environment }}-function with output from provision database"
        id: add_managed_id_function
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/provision/managed-id@feature/function-as-compaction
        with:
          environment: ${{ inputs.environment }}
          app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-function
          sql-server-resource-group: 'HVI-UTVIKLING-${{ inputs.environment }}-FELLES-rg'          
          sql-server-name: 'felles-db-server-${{inputs.environment}}-managedid'
          sql-connection-string: ${{ steps.provision_function_database.outputs.connection-string }}


      # - name: "Add managed identity to database for ${{ vars.APP_NAME }}-${{ inputs.environment }}-api with output from provision database"
      #   id: add_managed_id_api
      #   uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/provision/managed-id@feature/function-as-compaction
      #   with:
      #     environment: ${{ inputs.environment }}
      #     app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-api
      #     sql-server-resource-group: 'HVI-UTVIKLING-${{ inputs.environment }}-FELLES-rg'          
      #     sql-server-name: 'felles-db-server-${{inputs.environment}}-managedid'
      #     sql-connection-string: ${{ steps.provision_api_database.outputs.connection-string }}


          