name: "Provision og deploy til miljø"
on:
  workflow_call:
    inputs:
      environment:
        description: "Environment man vil deploye til"
        required: true
        type: string
env:
  APP_NAME: "orsl-kladdebok"
  WEB_ARTIFACT_NAME: "web-${{ inputs.environment }}"
jobs:
  deploy:
    name: "Deploy til ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: ${{ inputs.environment }}
    steps:
      - name: Print environment
        run: |
          echo "Deploying to environment: ${{ inputs.environment }}"
          echo "client id: ${{ secrets[format('AZURE_CLIENT_ID_{0}', inputs.environment)] }}"
          echo "tenant id: ${{ secrets[format('AZURE_TENANT_ID_{0}', inputs.environment)] }}"
          echo "subscription id: ${{ secrets[format('AZURE_SUBSCRIPTION_ID_{0}', inputs.environment)] }}"

      - name: Azure Login
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/azure-login@feature/function-as-compaction
        with:
          environment: ${{ inputs.environment }}
          azure-client-id: ${{ secrets[format('AZURE_CLIENT_ID_{0}', inputs.environment)] }}
          azure-tenant-id: ${{ secrets[format('AZURE_TENANT_ID_{0}', inputs.environment)] }}
          azure-subscription-id: ${{ secrets[format('AZURE_SUBSCRIPTION_ID_{0}', inputs.environment)] }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build angular app
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/build/angular-app@main
        with:
          project-directory: 'web'
          artifact-name: "web-${{ inputs.environment }}"
      - name: Provision angular app service for ${{ inputs.environment }}
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/provision/app-service@main
        with:
          environment: ${{ inputs.environment }}
          artifact-name: 'web'
          app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-web
          #set external-access to true if environment is QA or PROD
          external-access: ${{ contains(fromJSON('["QA", "PROD"]'), inputs.environment) }}
          resource-group: 'HVI-UTV-${{ inputs.environment }}-orsl-kladdebok-rg'
      - name: Provision API app service for ${{ inputs.environment }}
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/provision/app-service@main
        with:
          environment: ${{ inputs.environment }}
          artifact-name: 'api'
          app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-api
          external-access: false
          resource-group: 'HVI-UTV-${{ inputs.environment }}-orsl-kladdebok-rg'    
          app-service-plan-name: 'HVI-UTVIKLING-${{ inputs.environment }}-dotnet5-AppServicePlan'

      - name: Provision Function App for ${{ inputs.environment }}
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/provision/function@feature/function-as-compaction
        with:
          environment: ${{ inputs.environment }}
          function-app-name: ${{ vars.APP_NAME }}
          resource-group: 'HVI-UTV-${{ inputs.environment }}-orsl-kladdebok-rg'
          dotnet-version: 'v9.0'
          storage-account-name: 'orslkladdebok${{ inputs.environment }}sa'

      - name: Deploy Angular App to ${{ inputs.environment }}
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/deploy/angular-app@main
        with:          
          artifact-name: "web-${{ inputs.environment }}"   
          app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-web
          vars-json: ${{ toJSON(vars) }}

      - name: "Deploy API App to ${{ inputs.environment }}"  
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/deploy/dotnet-app@feature/function-as-compaction
        with:
          environment: ${{ inputs.environment }}
          artifact-name: 'api'
          app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-api
          connection-string-navn: 'KladdebokDbConnection'
          # Using a placeholder for connection string, replace with actual secret or output from DB deployment
          connection-string: ${{ secrets[format('SQL_CONNECTION_STRING_{0}', inputs.environment)] }}
          cors: 'https://orsl-kladdebok.azurewebsites.net, https://orsl-kladdebok.no'
          azure-appsettings: true
          vars-json: ${{ toJSON(vars) }}
          secrets-json: ${{ toJSON(secrets) }}
      
      - name: "Deploy Function App to ${{ inputs.environment }}"  
        uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/actions/deploy/function-app@feature/function-as-compaction
        with:
          function-app-name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-function
          environment: ${{ inputs.environment }}
          artifact-name: 'function-app'
          resource-group: 'HVI-UTV-${{ inputs.environment }}-orsl-kladdebok-rg'
          cors: 'https://www.bt.no, https://portal.azure.com'
          vars-json: ${{ toJSON(vars) }}
          secrets-json: ${{ toJSON(secrets) }}
  

  # deploy-db:
  #   name: "Deploy database til ${{ inputs.environment }}"
  #   uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/workflows/deploy-database.yaml@feature/db_elastic_pool
  #   needs: provision-app-service
  #   with:
  #     environment: ${{ inputs.environment }}
  #     db-name: ${{vars.APP_NAME}}-api
  #   secrets: inherit
  #   permissions:
  #     contents: read
  #     id-token: write

  # print-connection-string-from-deploy-db:
  #   name: "Print connection string for ${{ inputs.environment }}"
  #   runs-on: ubuntu-latest
  #   needs: deploy-db
  #   steps:
  #     - name: Print connection string
  #       run: |
  #         echo "Connection string for ${{ inputs.environment }}: ${{ needs.deploy-db.outputs.sqlconnectionstring }}"

  # add-managed-id:
  #   name: "Legg til managed identity for ${{ inputs.environment }}"
  #   needs: [deploy-db, provision-app-service, print-connection-string-from-deploy-db]
  #   uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/workflows/add-managedid-to-database.yaml@main
  #   with:
  #     environment: ${{ inputs.environment }}
  #     app-name: ${{ vars.APP_NAME }}-api
  #     sql-connection-string: ${{ needs.deploy-db.outputs.sqlconnectionstring }}
  #   secrets: inherit
  #   permissions:
  #     contents: read
  #     id-token: write

  # deploy-function:
          